<?php

namespace Nutritionist\FoodNutrientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoodNutrientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoodNutrientRepository extends EntityRepository
{
}
