<?php

namespace Nutritionist\NutrientBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Goutte\Client;

/**
 * NutrientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NutrientRepository extends EntityRepository
{

    public function loadNutrients($url = 'http://www.inran.it/646/tabelle_di_composizione_degli_alimenti.html'){
        $client = new Client();
        $crawler = $client->request('GET',$url);
        $nodes = $crawler->filter('#nutriente');
        $em = $this->getEntityManager();
        if ($nodes->count())
        {
            try{
                $total_nutrient = 0;
                $imported_nutrient = 0;
                $total_nutrient = $nodes->children()->count();
                foreach($nodes->children() as $node){
                    $nutrient = new Nutrient();
                    $nutrient->setName(trim($node->nodeValue));
                    $em->persist($nutrient);
                    $imported_nutrient +=1;
                }
                $nutrient = new Nutrient();
                $nutrient->setName('Zuccheri solubili (g/100g p.e.)');
                $em->persist($nutrient);
                $imported_nutrient +=1;

                $em->flush();
                return array('total_nutrient'=>$total_nutrient,'imported_nutrient'=> $imported_nutrient);

            }
            catch (\Exception $e){
                return $e;
            }
        }

    }

    public function findByNameLike($str = ''){
        if(strlen($str)){

            $qb = $this->createQueryBuilder('n');
            try{
            return $result = $qb->where($qb->expr()
                ->like('n.name',':name'))
                ->setParameter('name',$str."%")
                ->getQuery()
                ->getOneOrNullResult();


            }
            catch(\Exception $e){
                $nutrient = new Nutrient();
            }
            return $nutrient;

        }
    }
}
